### PR TITLE
Techfest 2023

### PR DESCRIPTION
**Pull request by AAndersn**

### CODE REVIEW

**Comment by afisher1** [comment]
Reviewing this PR. I have some questions though. I'm seeing changes in techfest_2023 that are already in main. It's not good when changes are in main and not in develop.

**Comment by craig8** [comment]
We have not made a release to main....We have only made pre-releases off develop

**Comment by afisher1** [comment]
Ok hold on. Most of the changes in this folder are already in develop. was this branch not created from develop?

**Comment by AAndersn** [comment]
not needed at current time. will rebase and release v1.0.0 at future data

**Pull request closed without merging**
